version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./api:/app
    depends_on:
      - store

  store:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data
