name: pm25-forecast
region: tor1
services:
- name: api
  github:
    repo: steveadams/pm25-forecast
    branch: main
    deploy_on_push: true
  source_dir: api
  dockerfile_path: api/Dockerfile
  http_port: 5000
  instance_size_slug: basic-xxs
  instance_count: 1
  routes:
  - path: /api
  envs:
  - key: PYTHONUNBUFFERED
    value: true
    scope: RUN_AND_BUILD_TIME
- name: frontend
  github:
    repo: steveadams/pm25-forecast
    branch: main
    deploy_on_push: true
  source_dir: frontend
  dockerfile_path: frontend/Dockerfile
  index_document: index.html
  http_port: 3000
  instance_size_slug: basic-xxs
  instance_count: 1
  routes:
  - path: /
  envs:
  - key: PUBLIC_URL
    value: /
    scope: RUN_AND_BUILD_TIME
databases:
- name: pm25-store
  engine: REDIS
  version: 7
  size: db-s-1vcpu-1gb
  num_nodes: 1
  region: tor1
