alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
ingress:
  rules:
  - component:
      name: forecast-api
    match:
      path:
        prefix: /
name: pm25-api
region: tor
services:
- environment_slug: python
  # envs:
  # - key: MAILCHIMP_API_KEY
  #   scope: RUN_AND_BUILD_TIME
  #   value: <MAILCHIMP_API_KEY>
  # - key: MAILCHIMP_LIST_ID
  #   scope: RUN_AND_BUILD_TIME
  #   value: <MAILCHIMP_LIST_ID>
  # - key: MAILCHIMP_SERVER_PREFIX
  #   scope: RUN_AND_BUILD_TIME
  #   value: <MAILCHIMP_SERVER_PREFIX>
  github:
    branch: main
    deploy_on_push: true
    repo: steveadams/pm25-forecast
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xs
  name: forecast-api
  run_command: gunicorn --worker-tmp-dir /dev/shm 'app:create_app()'
  source_dir: api
