alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
ingress:
  rules:
  - component:
      name: forecast-api
    match:
      path:
        prefix: /
name: pm25-api
region: tor
services:
- environment_slug: python
  envs:
  - key: MAILCHIMP_API_KEY
    scope: RUN_AND_BUILD_TIME
    value: f42fde5e8307aa665684c1eba75cb8cc-us21
  - key: MAILCHIMP_LIST_ID
    scope: RUN_AND_BUILD_TIME
    value: 9ac598921f
  - key: MAILCHIMP_SERVER_PREFIX
    scope: RUN_AND_BUILD_TIME
    value: us21
  github:
    branch: main
    deploy_on_push: true
    repo: steveadams/pm25-forecast
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xs
  name: forecast-api
  run_command: gunicorn --worker-tmp-dir /dev/shm 'app:create_app()'
  source_dir: api
